# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Wed Sep  7 19:49:36 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(419, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_PID = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_PID.setGeometry(QtCore.QRect(10, 180, 281, 211))
        self.groupBox_PID.setMouseTracking(False)
        self.groupBox_PID.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.groupBox_PID.setAutoFillBackground(True)
        self.groupBox_PID.setObjectName("groupBox_PID")
        self.label_KpAngle = QtWidgets.QLabel(self.groupBox_PID)
        self.label_KpAngle.setGeometry(QtCore.QRect(0, 50, 66, 17))
        self.label_KpAngle.setObjectName("label_KpAngle")
        self.label_KiAngle = QtWidgets.QLabel(self.groupBox_PID)
        self.label_KiAngle.setGeometry(QtCore.QRect(0, 80, 66, 17))
        self.label_KiAngle.setObjectName("label_KiAngle")
        self.doubleSpinBox_KpAngle = QtWidgets.QDoubleSpinBox(self.groupBox_PID)
        self.doubleSpinBox_KpAngle.setGeometry(QtCore.QRect(40, 40, 62, 27))
        self.doubleSpinBox_KpAngle.setDecimals(2)
        self.doubleSpinBox_KpAngle.setMinimum(0.0)
        self.doubleSpinBox_KpAngle.setSingleStep(0.5)
        self.doubleSpinBox_KpAngle.setObjectName("doubleSpinBox_KpAngle")
        self.doubleSpinBox_KiAngle = QtWidgets.QDoubleSpinBox(self.groupBox_PID)
        self.doubleSpinBox_KiAngle.setGeometry(QtCore.QRect(40, 70, 62, 27))
        self.doubleSpinBox_KiAngle.setDecimals(2)
        self.doubleSpinBox_KiAngle.setMinimum(0.0)
        self.doubleSpinBox_KiAngle.setSingleStep(0.1)
        self.doubleSpinBox_KiAngle.setObjectName("doubleSpinBox_KiAngle")
        self.label_KdAngle = QtWidgets.QLabel(self.groupBox_PID)
        self.label_KdAngle.setGeometry(QtCore.QRect(0, 110, 66, 17))
        self.label_KdAngle.setObjectName("label_KdAngle")
        self.doubleSpinBox_KdAngle = QtWidgets.QDoubleSpinBox(self.groupBox_PID)
        self.doubleSpinBox_KdAngle.setGeometry(QtCore.QRect(40, 100, 62, 27))
        self.doubleSpinBox_KdAngle.setDecimals(2)
        self.doubleSpinBox_KdAngle.setSingleStep(0.1)
        self.doubleSpinBox_KdAngle.setObjectName("doubleSpinBox_KdAngle")
        self.pushButton_sendPID = QtWidgets.QPushButton(self.groupBox_PID)
        self.pushButton_sendPID.setGeometry(QtCore.QRect(170, 170, 101, 23))
        self.pushButton_sendPID.setObjectName("pushButton_sendPID")
        self.label_KiSpeed = QtWidgets.QLabel(self.groupBox_PID)
        self.label_KiSpeed.setGeometry(QtCore.QRect(140, 80, 66, 17))
        self.label_KiSpeed.setObjectName("label_KiSpeed")
        self.label_KpSpeed = QtWidgets.QLabel(self.groupBox_PID)
        self.label_KpSpeed.setGeometry(QtCore.QRect(140, 50, 66, 17))
        self.label_KpSpeed.setObjectName("label_KpSpeed")
        self.doubleSpinBox_KiSpeed = QtWidgets.QDoubleSpinBox(self.groupBox_PID)
        self.doubleSpinBox_KiSpeed.setGeometry(QtCore.QRect(180, 70, 62, 27))
        self.doubleSpinBox_KiSpeed.setDecimals(2)
        self.doubleSpinBox_KiSpeed.setSingleStep(0.1)
        self.doubleSpinBox_KiSpeed.setObjectName("doubleSpinBox_KiSpeed")
        self.label_KdSpeed = QtWidgets.QLabel(self.groupBox_PID)
        self.label_KdSpeed.setGeometry(QtCore.QRect(140, 110, 66, 17))
        self.label_KdSpeed.setObjectName("label_KdSpeed")
        self.doubleSpinBox_KdSpeed = QtWidgets.QDoubleSpinBox(self.groupBox_PID)
        self.doubleSpinBox_KdSpeed.setGeometry(QtCore.QRect(180, 100, 62, 27))
        self.doubleSpinBox_KdSpeed.setDecimals(2)
        self.doubleSpinBox_KdSpeed.setSingleStep(0.1)
        self.doubleSpinBox_KdSpeed.setObjectName("doubleSpinBox_KdSpeed")
        self.doubleSpinBox_KpSpeed = QtWidgets.QDoubleSpinBox(self.groupBox_PID)
        self.doubleSpinBox_KpSpeed.setGeometry(QtCore.QRect(180, 40, 62, 27))
        self.doubleSpinBox_KpSpeed.setDecimals(2)
        self.doubleSpinBox_KpSpeed.setSingleStep(0.1)
        self.doubleSpinBox_KpSpeed.setObjectName("doubleSpinBox_KpSpeed")
        self.pushButton_sendPID_Zero = QtWidgets.QPushButton(self.groupBox_PID)
        self.pushButton_sendPID_Zero.setGeometry(QtCore.QRect(60, 170, 101, 23))
        self.pushButton_sendPID_Zero.setObjectName("pushButton_sendPID_Zero")
        self.label = QtWidgets.QLabel(self.groupBox_PID)
        self.label.setGeometry(QtCore.QRect(0, 20, 101, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_PID)
        self.label_2.setGeometry(QtCore.QRect(140, 20, 101, 17))
        self.label_2.setObjectName("label_2")
        self.doubleSpinBox_SetpointAngle = QtWidgets.QDoubleSpinBox(self.groupBox_PID)
        self.doubleSpinBox_SetpointAngle.setGeometry(QtCore.QRect(70, 130, 62, 27))
        self.doubleSpinBox_SetpointAngle.setDecimals(1)
        self.doubleSpinBox_SetpointAngle.setMinimum(-100.0)
        self.doubleSpinBox_SetpointAngle.setSingleStep(1.0)
        self.doubleSpinBox_SetpointAngle.setObjectName("doubleSpinBox_SetpointAngle")
        self.label_3 = QtWidgets.QLabel(self.groupBox_PID)
        self.label_3.setGeometry(QtCore.QRect(0, 140, 61, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_PID)
        self.label_4.setGeometry(QtCore.QRect(140, 140, 61, 17))
        self.label_4.setObjectName("label_4")
        self.doubleSpinBox_SetpointSpeed = QtWidgets.QDoubleSpinBox(self.groupBox_PID)
        self.doubleSpinBox_SetpointSpeed.setGeometry(QtCore.QRect(210, 130, 62, 27))
        self.doubleSpinBox_SetpointSpeed.setDecimals(1)
        self.doubleSpinBox_SetpointSpeed.setMinimum(-100.0)
        self.doubleSpinBox_SetpointSpeed.setSingleStep(1.0)
        self.doubleSpinBox_SetpointSpeed.setObjectName("doubleSpinBox_SetpointSpeed")
        self.groupBox_Orientation = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Orientation.setGeometry(QtCore.QRect(290, 180, 121, 121))
        self.groupBox_Orientation.setMouseTracking(False)
        self.groupBox_Orientation.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.groupBox_Orientation.setAutoFillBackground(True)
        self.groupBox_Orientation.setObjectName("groupBox_Orientation")
        self.label_roll = QtWidgets.QLabel(self.groupBox_Orientation)
        self.label_roll.setGeometry(QtCore.QRect(0, 30, 66, 17))
        self.label_roll.setObjectName("label_roll")
        self.label_pitch = QtWidgets.QLabel(self.groupBox_Orientation)
        self.label_pitch.setGeometry(QtCore.QRect(0, 60, 66, 17))
        self.label_pitch.setObjectName("label_pitch")
        self.label_yaw = QtWidgets.QLabel(self.groupBox_Orientation)
        self.label_yaw.setGeometry(QtCore.QRect(0, 90, 66, 17))
        self.label_yaw.setObjectName("label_yaw")
        self.lineEdit_roll = QtWidgets.QLineEdit(self.groupBox_Orientation)
        self.lineEdit_roll.setGeometry(QtCore.QRect(40, 20, 71, 27))
        self.lineEdit_roll.setObjectName("lineEdit_roll")
        self.lineEdit_pitch = QtWidgets.QLineEdit(self.groupBox_Orientation)
        self.lineEdit_pitch.setGeometry(QtCore.QRect(40, 50, 71, 27))
        self.lineEdit_pitch.setObjectName("lineEdit_pitch")
        self.lineEdit_yaw = QtWidgets.QLineEdit(self.groupBox_Orientation)
        self.lineEdit_yaw.setGeometry(QtCore.QRect(40, 80, 71, 27))
        self.lineEdit_yaw.setObjectName("lineEdit_yaw")
        self.groupBox_Motor = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Motor.setGeometry(QtCore.QRect(10, 380, 291, 151))
        self.groupBox_Motor.setMouseTracking(False)
        self.groupBox_Motor.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.groupBox_Motor.setAutoFillBackground(True)
        self.groupBox_Motor.setObjectName("groupBox_Motor")
        self.label_speedPid = QtWidgets.QLabel(self.groupBox_Motor)
        self.label_speedPid.setGeometry(QtCore.QRect(0, 30, 71, 17))
        self.label_speedPid.setObjectName("label_speedPid")
        self.label_speedRun = QtWidgets.QLabel(self.groupBox_Motor)
        self.label_speedRun.setGeometry(QtCore.QRect(170, 30, 66, 17))
        self.label_speedRun.setObjectName("label_speedRun")
        self.label_speedTurn = QtWidgets.QLabel(self.groupBox_Motor)
        self.label_speedTurn.setGeometry(QtCore.QRect(170, 60, 66, 17))
        self.label_speedTurn.setObjectName("label_speedTurn")
        self.lineEdit_speedPID = QtWidgets.QLineEdit(self.groupBox_Motor)
        self.lineEdit_speedPID.setGeometry(QtCore.QRect(80, 20, 71, 27))
        self.lineEdit_speedPID.setObjectName("lineEdit_speedPID")
        self.lineEdit_speedRun = QtWidgets.QLineEdit(self.groupBox_Motor)
        self.lineEdit_speedRun.setGeometry(QtCore.QRect(210, 20, 71, 27))
        self.lineEdit_speedRun.setObjectName("lineEdit_speedRun")
        self.lineEdit_speedTurn = QtWidgets.QLineEdit(self.groupBox_Motor)
        self.lineEdit_speedTurn.setGeometry(QtCore.QRect(210, 50, 71, 27))
        self.lineEdit_speedTurn.setObjectName("lineEdit_speedTurn")
        self.label_speedLeft = QtWidgets.QLabel(self.groupBox_Motor)
        self.label_speedLeft.setGeometry(QtCore.QRect(170, 90, 66, 17))
        self.label_speedLeft.setObjectName("label_speedLeft")
        self.lineEdit_speedLeft = QtWidgets.QLineEdit(self.groupBox_Motor)
        self.lineEdit_speedLeft.setGeometry(QtCore.QRect(210, 80, 71, 27))
        self.lineEdit_speedLeft.setObjectName("lineEdit_speedLeft")
        self.label_speedRight = QtWidgets.QLabel(self.groupBox_Motor)
        self.label_speedRight.setGeometry(QtCore.QRect(170, 120, 66, 17))
        self.label_speedRight.setObjectName("label_speedRight")
        self.lineEdit_speedRight = QtWidgets.QLineEdit(self.groupBox_Motor)
        self.lineEdit_speedRight.setGeometry(QtCore.QRect(210, 110, 71, 27))
        self.lineEdit_speedRight.setObjectName("lineEdit_speedRight")
        self.lineEdit_veloA = QtWidgets.QLineEdit(self.groupBox_Motor)
        self.lineEdit_veloA.setGeometry(QtCore.QRect(80, 80, 71, 27))
        self.lineEdit_veloA.setObjectName("lineEdit_veloA")
        self.lineEdit_anglePID = QtWidgets.QLineEdit(self.groupBox_Motor)
        self.lineEdit_anglePID.setGeometry(QtCore.QRect(80, 50, 71, 27))
        self.lineEdit_anglePID.setObjectName("lineEdit_anglePID")
        self.label_veloB = QtWidgets.QLabel(self.groupBox_Motor)
        self.label_veloB.setGeometry(QtCore.QRect(0, 120, 66, 17))
        self.label_veloB.setObjectName("label_veloB")
        self.lineEdit_veloB = QtWidgets.QLineEdit(self.groupBox_Motor)
        self.lineEdit_veloB.setGeometry(QtCore.QRect(80, 110, 71, 27))
        self.lineEdit_veloB.setObjectName("lineEdit_veloB")
        self.label_anglePID = QtWidgets.QLabel(self.groupBox_Motor)
        self.label_anglePID.setGeometry(QtCore.QRect(0, 60, 81, 17))
        self.label_anglePID.setObjectName("label_anglePID")
        self.label_veloA = QtWidgets.QLabel(self.groupBox_Motor)
        self.label_veloA.setGeometry(QtCore.QRect(0, 90, 66, 17))
        self.label_veloA.setObjectName("label_veloA")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 411, 171))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_server_settings = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_server_settings.setGeometry(QtCore.QRect(0, 20, 201, 111))
        self.groupBox_server_settings.setMouseTracking(False)
        self.groupBox_server_settings.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.groupBox_server_settings.setAutoFillBackground(True)
        self.groupBox_server_settings.setObjectName("groupBox_server_settings")
        self.label_serverIP = QtWidgets.QLabel(self.groupBox_server_settings)
        self.label_serverIP.setGeometry(QtCore.QRect(0, 30, 66, 17))
        self.label_serverIP.setObjectName("label_serverIP")
        self.label_serverPort = QtWidgets.QLabel(self.groupBox_server_settings)
        self.label_serverPort.setGeometry(QtCore.QRect(0, 60, 66, 17))
        self.label_serverPort.setObjectName("label_serverPort")
        self.lineEdit_serverIP = QtWidgets.QLineEdit(self.groupBox_server_settings)
        self.lineEdit_serverIP.setGeometry(QtCore.QRect(70, 20, 113, 27))
        self.lineEdit_serverIP.setObjectName("lineEdit_serverIP")
        self.lineEdit_serverPort = QtWidgets.QLineEdit(self.groupBox_server_settings)
        self.lineEdit_serverPort.setGeometry(QtCore.QRect(70, 50, 51, 27))
        self.lineEdit_serverPort.setInputMask("")
        self.lineEdit_serverPort.setObjectName("lineEdit_serverPort")
        self.pushButton_serverEnable = QtWidgets.QPushButton(self.groupBox_server_settings)
        self.pushButton_serverEnable.setGeometry(QtCore.QRect(70, 80, 111, 23))
        self.pushButton_serverEnable.setObjectName("pushButton_serverEnable")
        self.groupBox_client_settings = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_client_settings.setGeometry(QtCore.QRect(210, 20, 201, 111))
        self.groupBox_client_settings.setMouseTracking(False)
        self.groupBox_client_settings.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.groupBox_client_settings.setAutoFillBackground(True)
        self.groupBox_client_settings.setObjectName("groupBox_client_settings")
        self.label_clientIP = QtWidgets.QLabel(self.groupBox_client_settings)
        self.label_clientIP.setGeometry(QtCore.QRect(0, 30, 66, 17))
        self.label_clientIP.setObjectName("label_clientIP")
        self.label_clientPort = QtWidgets.QLabel(self.groupBox_client_settings)
        self.label_clientPort.setGeometry(QtCore.QRect(0, 60, 66, 17))
        self.label_clientPort.setObjectName("label_clientPort")
        self.lineEdit_clientIP = QtWidgets.QLineEdit(self.groupBox_client_settings)
        self.lineEdit_clientIP.setGeometry(QtCore.QRect(70, 20, 113, 27))
        self.lineEdit_clientIP.setObjectName("lineEdit_clientIP")
        self.lineEdit_clientPort = QtWidgets.QLineEdit(self.groupBox_client_settings)
        self.lineEdit_clientPort.setGeometry(QtCore.QRect(70, 50, 51, 27))
        self.lineEdit_clientPort.setObjectName("lineEdit_clientPort")
        self.pushButton_clientEnable = QtWidgets.QPushButton(self.groupBox_client_settings)
        self.pushButton_clientEnable.setGeometry(QtCore.QRect(70, 80, 111, 23))
        self.pushButton_clientEnable.setObjectName("pushButton_clientEnable")
        self.pushButton_restartUDP = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_restartUDP.setGeometry(QtCore.QRect(280, 130, 111, 23))
        self.pushButton_restartUDP.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_restartUDP.setObjectName("pushButton_restartUDP")
        self.pushButton_chart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chart.setGeometry(QtCore.QRect(310, 400, 101, 23))
        self.pushButton_chart.setObjectName("pushButton_chart")
        self.pushButton_3dModel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3dModel.setGeometry(QtCore.QRect(310, 440, 101, 23))
        self.pushButton_3dModel.setObjectName("pushButton_3dModel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 419, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wireless monitor"))
        self.groupBox_PID.setTitle(_translate("MainWindow", "PID Controllers"))
        self.label_KpAngle.setText(_translate("MainWindow", "Kp:"))
        self.label_KiAngle.setText(_translate("MainWindow", "Ki:"))
        self.label_KdAngle.setText(_translate("MainWindow", "Kd:"))
        self.pushButton_sendPID.setText(_translate("MainWindow", "Send..."))
        self.label_KiSpeed.setText(_translate("MainWindow", "Ki:"))
        self.label_KpSpeed.setText(_translate("MainWindow", "Kp:"))
        self.label_KdSpeed.setText(_translate("MainWindow", "Kd:"))
        self.pushButton_sendPID_Zero.setText(_translate("MainWindow", "Zero"))
        self.label.setText(_translate("MainWindow", "Angle Control"))
        self.label_2.setText(_translate("MainWindow", "Speed Control"))
        self.label_3.setText(_translate("MainWindow", "Setpoint:"))
        self.label_4.setText(_translate("MainWindow", "Setpoint:"))
        self.groupBox_Orientation.setTitle(_translate("MainWindow", "Orientation"))
        self.label_roll.setText(_translate("MainWindow", "Roll:"))
        self.label_pitch.setText(_translate("MainWindow", "Pitch:"))
        self.label_yaw.setText(_translate("MainWindow", "Yaw:"))
        self.groupBox_Motor.setTitle(_translate("MainWindow", "Motor speed"))
        self.label_speedPid.setText(_translate("MainWindow", "PID Speed"))
        self.label_speedRun.setText(_translate("MainWindow", "Run"))
        self.label_speedTurn.setText(_translate("MainWindow", "Turn"))
        self.label_speedLeft.setText(_translate("MainWindow", "Left"))
        self.label_speedRight.setText(_translate("MainWindow", "Right"))
        self.label_veloB.setText(_translate("MainWindow", "Velo B"))
        self.label_anglePID.setText(_translate("MainWindow", "Run Angle"))
        self.label_veloA.setText(_translate("MainWindow", "Velo A"))
        self.groupBox.setTitle(_translate("MainWindow", "Connection settings"))
        self.groupBox_server_settings.setTitle(_translate("MainWindow", "Server UDP"))
        self.label_serverIP.setText(_translate("MainWindow", "IP Addr:"))
        self.label_serverPort.setText(_translate("MainWindow", "Port:"))
        self.lineEdit_serverIP.setText(_translate("MainWindow", "192.168.1.35"))
        self.lineEdit_serverPort.setText(_translate("MainWindow", "5000"))
        self.pushButton_serverEnable.setText(_translate("MainWindow", "Enable"))
        self.groupBox_client_settings.setTitle(_translate("MainWindow", "Client UDP"))
        self.label_clientIP.setText(_translate("MainWindow", "IP Addr:"))
        self.label_clientPort.setText(_translate("MainWindow", "Port:"))
        self.lineEdit_clientIP.setText(_translate("MainWindow", "192.168.1.49"))
        self.lineEdit_clientPort.setText(_translate("MainWindow", "5001"))
        self.pushButton_clientEnable.setText(_translate("MainWindow", "Enable"))
        self.pushButton_restartUDP.setText(_translate("MainWindow", "Restart UDP..."))
        self.pushButton_chart.setText(_translate("MainWindow", "Chart..."))
        self.pushButton_3dModel.setText(_translate("MainWindow", "3D Model..."))

