# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 407)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 611, 341))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 381, 131))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 20, 191, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(0, 30, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 67, 17))
        self.label_2.setObjectName("label_2")
        self.lineEdit_IP_server = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_IP_server.setGeometry(QtCore.QRect(70, 20, 113, 27))
        self.lineEdit_IP_server.setObjectName("lineEdit_IP_server")
        self.lineEdit_port_server = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_port_server.setGeometry(QtCore.QRect(70, 50, 61, 27))
        self.lineEdit_port_server.setObjectName("lineEdit_port_server")
        self.pushButton_en_server = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_en_server.setGeometry(QtCore.QRect(70, 80, 111, 27))
        self.pushButton_en_server.setObjectName("pushButton_en_server")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(190, 20, 191, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(0, 30, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(0, 60, 67, 17))
        self.label_4.setObjectName("label_4")
        self.lineEdit_ip_client = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_ip_client.setGeometry(QtCore.QRect(70, 20, 113, 27))
        self.lineEdit_ip_client.setObjectName("lineEdit_ip_client")
        self.lineEdit_port_client = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_port_client.setGeometry(QtCore.QRect(70, 50, 61, 27))
        self.lineEdit_port_client.setObjectName("lineEdit_port_client")
        self.pushButton_en_client = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_en_client.setGeometry(QtCore.QRect(70, 80, 111, 27))
        self.pushButton_en_client.setObjectName("pushButton_en_client")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 159, 241, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(0, 30, 67, 17))
        self.label_5.setObjectName("label_5")
        self.lineEdit_roll = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_roll.setGeometry(QtCore.QRect(50, 20, 71, 27))
        self.lineEdit_roll.setObjectName("lineEdit_roll")
        self.lineEdit_pitch = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_pitch.setGeometry(QtCore.QRect(50, 50, 71, 27))
        self.lineEdit_pitch.setObjectName("lineEdit_pitch")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(0, 60, 67, 17))
        self.label_6.setObjectName("label_6")
        self.lineEdit_yaw = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_yaw.setGeometry(QtCore.QRect(50, 80, 71, 27))
        self.lineEdit_yaw.setObjectName("lineEdit_yaw")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(0, 90, 67, 17))
        self.label_7.setObjectName("label_7")
        self.pushButton_3d_model = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_3d_model.setGeometry(QtCore.QRect(140, 70, 91, 31))
        self.pushButton_3d_model.setObjectName("pushButton_3d_model")
        self.pushButton_chart_orientation = QtWidgets.QPushButton(self.tab)
        self.pushButton_chart_orientation.setGeometry(QtCore.QRect(160, 180, 91, 31))
        self.pushButton_chart_orientation.setObjectName("pushButton_chart_orientation")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(270, 160, 141, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(0, 30, 67, 17))
        self.label_8.setObjectName("label_8")
        self.lineEdit_velocA = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_velocA.setGeometry(QtCore.QRect(70, 20, 71, 27))
        self.lineEdit_velocA.setObjectName("lineEdit_velocA")
        self.lineEdit_velocB = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_velocB.setGeometry(QtCore.QRect(70, 50, 71, 27))
        self.lineEdit_velocB.setObjectName("lineEdit_velocB")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(0, 60, 67, 17))
        self.label_9.setObjectName("label_9")
        self.lineEdit_veloc_avg = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_veloc_avg.setGeometry(QtCore.QRect(70, 80, 71, 27))
        self.lineEdit_veloc_avg.setObjectName("lineEdit_veloc_avg")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(0, 90, 67, 17))
        self.label_10.setObjectName("label_10")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(420, 160, 191, 111))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(0, 30, 67, 17))
        self.label_11.setObjectName("label_11")
        self.lineEdit_analog1_horiz = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_analog1_horiz.setGeometry(QtCore.QRect(70, 20, 51, 27))
        self.lineEdit_analog1_horiz.setObjectName("lineEdit_analog1_horiz")
        self.lineEdit_analog1_vertical = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_analog1_vertical.setGeometry(QtCore.QRect(130, 20, 51, 27))
        self.lineEdit_analog1_vertical.setObjectName("lineEdit_analog1_vertical")
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setGeometry(QtCore.QRect(0, 60, 67, 17))
        self.label_12.setObjectName("label_12")
        self.lineEdit_analog2_vertical = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_analog2_vertical.setGeometry(QtCore.QRect(130, 50, 51, 27))
        self.lineEdit_analog2_vertical.setObjectName("lineEdit_analog2_vertical")
        self.lineEdit_analog2_horiz = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_analog2_horiz.setGeometry(QtCore.QRect(70, 50, 51, 27))
        self.lineEdit_analog2_horiz.setObjectName("lineEdit_analog2_horiz")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 301, 151))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setGeometry(QtCore.QRect(0, 30, 67, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(0, 60, 67, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setGeometry(QtCore.QRect(0, 90, 67, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(150, 120, 67, 17))
        self.label_16.setObjectName("label_16")
        self.doubleSpinBox_angle_kp = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_angle_kp.setGeometry(QtCore.QRect(60, 20, 69, 27))
        self.doubleSpinBox_angle_kp.setDecimals(2)
        self.doubleSpinBox_angle_kp.setSingleStep(0.5)
        self.doubleSpinBox_angle_kp.setObjectName("doubleSpinBox_angle_kp")
        self.doubleSpinBox_angle_ki = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_angle_ki.setGeometry(QtCore.QRect(60, 50, 69, 27))
        self.doubleSpinBox_angle_ki.setSingleStep(0.1)
        self.doubleSpinBox_angle_ki.setObjectName("doubleSpinBox_angle_ki")
        self.doubleSpinBox_angle_kd = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_angle_kd.setGeometry(QtCore.QRect(60, 80, 69, 27))
        self.doubleSpinBox_angle_kd.setSingleStep(0.1)
        self.doubleSpinBox_angle_kd.setObjectName("doubleSpinBox_angle_kd")
        self.doubleSpinBox_angle_setpoint = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_angle_setpoint.setGeometry(QtCore.QRect(220, 110, 69, 27))
        self.doubleSpinBox_angle_setpoint.setMinimum(-100.0)
        self.doubleSpinBox_angle_setpoint.setSingleStep(0.5)
        self.doubleSpinBox_angle_setpoint.setObjectName("doubleSpinBox_angle_setpoint")
        self.pushButton_angle_zero = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_angle_zero.setGeometry(QtCore.QRect(78, 110, 61, 27))
        self.pushButton_angle_zero.setObjectName("pushButton_angle_zero")
        self.pushButton_angle_set = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_angle_set.setGeometry(QtCore.QRect(0, 110, 61, 27))
        self.pushButton_angle_set.setObjectName("pushButton_angle_set")
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setGeometry(QtCore.QRect(160, 30, 67, 17))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setGeometry(QtCore.QRect(160, 60, 67, 17))
        self.label_21.setObjectName("label_21")
        self.doubleSpinBox_angle_kd_Aggr = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_angle_kd_Aggr.setGeometry(QtCore.QRect(220, 80, 69, 27))
        self.doubleSpinBox_angle_kd_Aggr.setSingleStep(0.1)
        self.doubleSpinBox_angle_kd_Aggr.setObjectName("doubleSpinBox_angle_kd_Aggr")
        self.doubleSpinBox_angle_kp_Aggr = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_angle_kp_Aggr.setGeometry(QtCore.QRect(220, 20, 69, 27))
        self.doubleSpinBox_angle_kp_Aggr.setDecimals(2)
        self.doubleSpinBox_angle_kp_Aggr.setSingleStep(0.5)
        self.doubleSpinBox_angle_kp_Aggr.setObjectName("doubleSpinBox_angle_kp_Aggr")
        self.doubleSpinBox_angle_ki_Aggr = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_angle_ki_Aggr.setGeometry(QtCore.QRect(220, 50, 69, 27))
        self.doubleSpinBox_angle_ki_Aggr.setSingleStep(0.1)
        self.doubleSpinBox_angle_ki_Aggr.setObjectName("doubleSpinBox_angle_ki_Aggr")
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setGeometry(QtCore.QRect(160, 90, 67, 17))
        self.label_22.setObjectName("label_22")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(330, 10, 151, 151))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_17 = QtWidgets.QLabel(self.groupBox_8)
        self.label_17.setGeometry(QtCore.QRect(0, 30, 67, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_8)
        self.label_18.setGeometry(QtCore.QRect(0, 60, 67, 17))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setGeometry(QtCore.QRect(0, 90, 67, 17))
        self.label_19.setObjectName("label_19")
        self.doubleSpinBox_speed_kp = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox_speed_kp.setGeometry(QtCore.QRect(40, 20, 69, 27))
        self.doubleSpinBox_speed_kp.setSingleStep(0.1)
        self.doubleSpinBox_speed_kp.setObjectName("doubleSpinBox_speed_kp")
        self.doubleSpinBox_speed_ki = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox_speed_ki.setGeometry(QtCore.QRect(40, 50, 69, 27))
        self.doubleSpinBox_speed_ki.setSingleStep(0.1)
        self.doubleSpinBox_speed_ki.setObjectName("doubleSpinBox_speed_ki")
        self.doubleSpinBox_speed_kd = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox_speed_kd.setGeometry(QtCore.QRect(40, 80, 69, 27))
        self.doubleSpinBox_speed_kd.setSingleStep(0.1)
        self.doubleSpinBox_speed_kd.setObjectName("doubleSpinBox_speed_kd")
        self.pushButton_speed_zero = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_speed_zero.setGeometry(QtCore.QRect(80, 110, 61, 27))
        self.pushButton_speed_zero.setObjectName("pushButton_speed_zero")
        self.pushButton_speed_set = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_speed_set.setGeometry(QtCore.QRect(2, 110, 61, 27))
        self.pushButton_speed_set.setObjectName("pushButton_speed_set")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 160, 121, 131))
        self.groupBox_9.setObjectName("groupBox_9")
        self.checkBox_angle_out = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_angle_out.setGeometry(QtCore.QRect(0, 30, 121, 22))
        self.checkBox_angle_out.setObjectName("checkBox_angle_out")
        self.checkBox_speed_out = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_speed_out.setGeometry(QtCore.QRect(0, 60, 121, 22))
        self.checkBox_speed_out.setObjectName("checkBox_speed_out")
        self.pushButton_chart_pid = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_chart_pid.setGeometry(QtCore.QRect(30, 90, 91, 31))
        self.pushButton_chart_pid.setObjectName("pushButton_chart_pid")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_10.setGeometry(QtCore.QRect(0, 20, 171, 191))
        self.groupBox_10.setObjectName("groupBox_10")
        self.dial = QtWidgets.QDial(self.groupBox_10)
        self.dial.setGeometry(QtCore.QRect(80, 70, 50, 64))
        self.dial.setObjectName("dial")
        self.verticalSlider = QtWidgets.QSlider(self.groupBox_10)
        self.verticalSlider.setGeometry(QtCore.QRect(10, 20, 29, 160))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_11.setGeometry(QtCore.QRect(200, 20, 171, 191))
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalSlider_2 = QtWidgets.QSlider(self.groupBox_11)
        self.verticalSlider_2.setGeometry(QtCore.QRect(10, 20, 29, 160))
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.verticalSlider_3 = QtWidgets.QSlider(self.groupBox_11)
        self.verticalSlider_3.setGeometry(QtCore.QRect(50, 20, 29, 160))
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wifi Monitor"))
        self.groupBox.setTitle(_translate("MainWindow", "Connection settings"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Server UDP"))
        self.label.setText(_translate("MainWindow", "IP Addr:"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.lineEdit_IP_server.setText(_translate("MainWindow", "192.168.1.35"))
        self.lineEdit_port_server.setText(_translate("MainWindow", "5000"))
        self.pushButton_en_server.setText(_translate("MainWindow", "Enable"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Client UDP"))
        self.label_3.setText(_translate("MainWindow", "IP Addr:"))
        self.label_4.setText(_translate("MainWindow", "Port:"))
        self.lineEdit_ip_client.setText(_translate("MainWindow", "192.168.1.49"))
        self.lineEdit_port_client.setText(_translate("MainWindow", "5001"))
        self.pushButton_en_client.setText(_translate("MainWindow", "Enable"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Orientation"))
        self.label_5.setText(_translate("MainWindow", "Roll:"))
        self.label_6.setText(_translate("MainWindow", "Pitch"))
        self.label_7.setText(_translate("MainWindow", "Yaw"))
        self.pushButton_3d_model.setText(_translate("MainWindow", "3D Model..."))
        self.pushButton_chart_orientation.setText(_translate("MainWindow", "Chart..."))
        self.groupBox_5.setTitle(_translate("MainWindow", "Motor Speed"))
        self.label_8.setText(_translate("MainWindow", "Velo A:"))
        self.label_9.setText(_translate("MainWindow", "Velo B:"))
        self.label_10.setText(_translate("MainWindow", "Average:"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Controller "))
        self.label_11.setText(_translate("MainWindow", "Analog 1:"))
        self.label_12.setText(_translate("MainWindow", "Analog 2:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Monitor"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Angle Control"))
        self.label_13.setText(_translate("MainWindow", "Kp Cons:"))
        self.label_14.setText(_translate("MainWindow", "Ki Cons:"))
        self.label_15.setText(_translate("MainWindow", "Kd Cons:"))
        self.label_16.setText(_translate("MainWindow", "Setpoint:"))
        self.pushButton_angle_zero.setText(_translate("MainWindow", "Zero"))
        self.pushButton_angle_set.setText(_translate("MainWindow", "Set"))
        self.label_20.setText(_translate("MainWindow", "Kp Aggr:"))
        self.label_21.setText(_translate("MainWindow", "Ki Aggr:"))
        self.label_22.setText(_translate("MainWindow", "Kd Aggr:"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Speed Control"))
        self.label_17.setText(_translate("MainWindow", "Kp:"))
        self.label_18.setText(_translate("MainWindow", "Ki:"))
        self.label_19.setText(_translate("MainWindow", "Kd:"))
        self.pushButton_speed_zero.setText(_translate("MainWindow", "Zero"))
        self.pushButton_speed_set.setText(_translate("MainWindow", "Set"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Chart"))
        self.checkBox_angle_out.setText(_translate("MainWindow", "Angle output"))
        self.checkBox_speed_out.setText(_translate("MainWindow", "Speed output"))
        self.pushButton_chart_pid.setText(_translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "PID"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Body"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Head"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Control"))

